site_name: Tiếng Ý - Khu học mở
site_description: Tự học Tiếng Ý thông qua Immersion và Comprehensible Input, hoàn toàn miễn phí.
site_author: duykhanh471
site_url: https://daihocmo.github.io
repo_name: Đóng góp & Chỉnh sửa trang
repo_url: https://github.com/daihocmo/tieng-y

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn': 
    - 'Tự học Tiếng Ý': 'guide.md'
    - 'Hướng dẫn đơn ngữ': 'monolingual.md'
  - 'Yomitan':
    - 'Hướng dẫn cài đặt': 'yomitan.md'
    - 'Mining với Anki & Yomitan': 'mining.md'
  - 'Tài nguyên': 
    - 'Học': 'resources.md'
    - 'Comprehensible Input': 'comprehensible-input.md'
    - 'Nội dung Tiếng Ý': 'recommendations.md'
    - 'Tham gia cộng đồng trên Discord': 'join.md'
  
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo.png
  favicon: img/logo.png
  custom_dir: overrides/
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

plugins:
  - search
  - open-in-new-tab
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  generator: false
  homepage: https://daihocmo.github.io/

copyright: |
  <a href="https://daihocmo.github.io">Một dự án của Khu học mở</a>